name: Tear Down Main Infrastructure

on: workflow_dispatch

jobs:
  teardown:
    runs-on: ubuntu-latest
    name: Tear Down Infrastructure

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialise Backend
        id: init-backend
        working-directory: ./SSG-API-Testing-Application-v2/deploy/dev/create-backend
        run: terraform init

      - name: Initialise Main Infrastructure
        id: init-main
        working-directory: ./SSG-API-Testing-Application-v2/deploy/prod/main-infrastructure
        run: terraform init -backend-config="access_key=$AWS_ACCESS_KEY_ID" -backend-config="secret_key=$AWS_SECRET_ACCESS_KEY"

      - name: Destroy Main Infrastructure
        working-directory: ./SSG-API-Testing-Application-v2/deploy/dev/main-infrastructure
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: terraform destroy -auto-approve
